# Generated by Django 5.2.3 on 2025-06-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0002_streamplatform_watchlist_delete_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="description",
            new_name="storyline",
        ),
    ]
