# Generated by Django 5.2.3 on 2025-06-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0003_rename_description_watchlist_storyline"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamplatform",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
