# Generated by Django 5.2.3 on 2025-06-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0006_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="titile",
            new_name="title",
        ),
    ]
